version: "2"

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - errcheck
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - wastedassign
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
